Repository logos-co/nomos-specs, pull requests merged in 2024-01, with the labels that each got.

#41 Use package prefix to run unittests at the root dir
  .github/workflows/ci.yml
  carnot/beaconized_carnot.py
  carnot/overlay.py
  carnot/test_beacon_verification.py
  carnot/test_beaconized_carnot.py
  carnot/test_happy_path.py
  carnot/test_tree_overlay.py
  carnot/test_unhappy_path.py
  carnot/tree_overlay.py
Labels: enhancement

#48 Use Python 3.12 and install setuptools
  .github/workflows/ci.yml
  requirements.txt
Labels: enhancement

#49 Mixnet: Packet delay in mix node
  mixnet/mixnet.py
  mixnet/node.py
  mixnet/poisson.py
  mixnet/test_node.py
  mixnet/test_packet.py
  requirements.txt
Labels: enhancement

#50 Mixnet: mix client emission
  mixnet/client.py
  mixnet/test_client.py
  mixnet/test_node.py
Labels: enhancement

#36 Fix: Deterministic committees Ids generation
  carnot/tree_overlay.py
Labels: bug

#37 Specify shuffling algorithm
  carnot/tree_overlay.py
Labels: documentation
